apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  gateways:
  - rhom-ingress.istio-system.svc.cluster.local
  hosts:
  - {{ .Values.service.dns }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: "{{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local"
        subset: stable
        port:
          number: {{ .Values.service.port }}
      weight: 90
    - destination:
        host: "{{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local"
        subset: canary
        port:
          number: {{ .Values.service.port }}
      weight: 10
